env:
  - GO111MODULE=on

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - amd64
    - arm64
  mod_timestamp: '{{ .CommitTimestamp }}'
  main: ./cmd/gearman-exporter

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - README.md
      - LICENSE